server:
  port: 6000

spring:
  application:
    name: PULLER-SERVICE
  config:
    import: "configserver:http://config-server:9091"
  kafka:
    bootstrap-servers: broker-1:9092
    template:
      default-topic: "datahub.team.avro.topic.v1"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081

avro:
  topic:
    name: "datahub.team.avro.topic.v1"
